
stages:
    - deploy

staging:
    type: deploy
    stage: deploy
    image: ruby:latest
    script:
      - gem install faraday -v 1.8.0
      - gem install dpl
      - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    only:
        - development

